import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "@/lib/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          {children}
        </AuthProvider>

        <Toaster
          position="top-right"
          toastOptions={{
            style: {
              background: '#FFD700', // Gold background for all toasts (can override per type)
              color: '#6A0DAD', // Purple text for all toasts
              fontWeight: '500',
              boxShadow: '0 4px 14px rgba(106, 13, 173, 0.5)', // Purple-ish shadow
            },
            success: {
              style: {
                background: '#6A0DAD', // Purple bg for success
                color: '#FFD700',       // Gold text for success
              },
              iconTheme: {
                primary: '#FFD700',   // Gold icon color
                secondary: '#6A0DAD', // Purple icon background
              },
            },
            error: {
              style: {
                background: '#ff4d4f', // Red bg for errors
                color: '#fff',         // White text for errors
              },
              iconTheme: {
                primary: '#fff',       // White icon color
                secondary: '#ff4d4f',  // Red icon background
              },
            },
          }}
        />

      </body>
    </html>
  );
}
